---
kind: pipeline
type: docker
name: Sync master
node:
  drone: ch1
trigger:
  branch:
  - main
  event:
  - push

steps:
- name: build
  image: ch1ch1/drone-hugo
  settings:
    hugo_version: 0.89.3
  pull: always
- name: deploy
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: websitesynchost
    user:
      from_secret: id_user
    key:
      from_secret: id_rsadeploy
    passphrase:
      from_secret: id_rsapassphrase
    target:
        from_secret: path
    overwrite: true
-   name: purge cache
    image: jetrails/drone-cloudflare-caching
    settings:
        api_token:
            from_secret: cloudflare_token
        zone_identifier:
            from_secret: cloudflare_zone_identifier
        action: purge_everything
- name: notification
  image: plugins/webhook
  settings:
    urls:
      from_secret: webhookgotify
    content_type: application/json
    template: |
      {
       "message": "{{ repo.owner }} as updated {{ repo.name }} with {{ build.status }}.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [success, failure]

---
kind: pipeline
type: docker
name: Sync dev
node:
  drone: ch1
trigger:
  branch:
  - dev
  event:
  - push

steps:
- name: build
  image: ch1ch1/drone-hugo
  settings:
    hugo_version: 0.89.3
  pull: always
- name: deploy
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: websitesynchost
    user:
      from_secret: id_user
    key:
      from_secret: id_rsadeploy
    passphrase:
      from_secret: id_rsapassphrase
    target:
        from_secret: pathdev
    overwrite: true
-   name: purge cache
    image: jetrails/drone-cloudflare-caching
    settings:
        api_token:
            from_secret: cloudflare_token
        zone_identifier:
            from_secret: cloudflare_zone_identifier
        action: purge_everything
- name: notification
  image: plugins/webhook
  settings:
    urls:
      from_secret: webhookgotify
    content_type: application/json
    template: |
      {
       "message": "{{ repo.owner }} as updated {{ repo.name }} with {{ build.status }}.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [success, failure]
---
kind: signature
hmac: 17052f043abb718ef223f7dd80542ada8d2b739fba8a120bd9915b44c345d7bf

...
